name: Deploy to S3

on:
  pull_request:
    branches: [ staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: s3_developercenter

    steps:
    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}

    - name: Sync files to S3
      run: |
        aws s3 sync ./front-end s3://${{ secrets.S3_BUCKET_NAME }}/${{ secrets.S3_FOLDER_PATH }}/ \
          --delete

